package web

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"gorm.io/gorm"

	"scrutineer/internal/db"
)

// repoReport renders a shareable markdown document covering everything the
// repo page shows: identity, threat model, findings (with six-step prose,
// scoring fields, notes, communications, references), packages, advisories,
// dependents, dependencies, and maintainers. Served as text/markdown with
// a filename hint so clicking the download button saves a file.
func (s *Server) repoReport(w http.ResponseWriter, r *http.Request) {
	var repo db.Repository
	if err := s.DB.First(&repo, r.PathValue("id")).Error; err != nil {
		http.NotFound(w, r)
		return
	}

	body := renderRepoReport(s.DB, &repo)

	filename := fmt.Sprintf("scrutineer-%s-%s.md",
		sanitiseFilename(repo.Name),
		time.Now().UTC().Format("20060102"))
	w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
	w.Header().Set("Content-Disposition", `attachment; filename="`+filename+`"`)
	_, _ = w.Write([]byte(body))
}

func renderRepoReport(gdb *gorm.DB, repo *db.Repository) string {
	var b strings.Builder
	writeReportHeader(&b, repo)
	writeReportMetadata(&b, repo)

	latest, threatModel := latestDeepDive(gdb, repo.ID)
	writeReportThreatModel(&b, latest, threatModel)

	writeReportFindings(&b, gdb, repo.ID, latest)
	writeReportPackages(&b, gdb, repo.ID)
	writeReportAdvisories(&b, gdb, repo.ID)
	writeReportDependents(&b, gdb, repo.ID)
	writeReportDependencies(&b, gdb, repo.ID)
	writeReportMaintainers(&b, gdb, repo.ID)

	return b.String()
}

func writeReportHeader(b *strings.Builder, repo *db.Repository) {
	fmt.Fprintf(b, "# %s\n\n", firstNonEmpty(repo.FullName, repo.Name, repo.URL))
	fmt.Fprintf(b, "<%s>\n\n", repo.URL)
	if repo.Description != "" {
		fmt.Fprintf(b, "%s\n\n", repo.Description)
	}
	fmt.Fprintf(b, "Generated by [scrutineer](https://github.com/alpha-omega-security/scrutineer) at %s UTC.\n\n",
		time.Now().UTC().Format("2006-01-02 15:04"))
	fmt.Fprintf(b, "---\n\n")
}

func writeReportMetadata(b *strings.Builder, repo *db.Repository) {
	fmt.Fprintf(b, "## Repository metadata\n\n")
	rows := [][2]string{
		{"URL", repo.URL},
		{"Full name", repo.FullName},
		{"Owner", repo.Owner},
		{"Default branch", repo.DefaultBranch},
		{"Languages", repo.Languages},
		{"License", repo.License},
		{"Stars", fmt.Sprintf("%d", repo.Stars)},
		{"Forks", fmt.Sprintf("%d", repo.Forks)},
		{"Archived", fmt.Sprintf("%t", repo.Archived)},
	}
	if repo.PushedAt != nil {
		rows = append(rows, [2]string{"Last pushed", repo.PushedAt.UTC().Format(time.RFC3339)})
	}
	fmt.Fprintf(b, "| Field | Value |\n|---|---|\n")
	for _, r := range rows {
		if r[1] == "" {
			continue
		}
		fmt.Fprintf(b, "| %s | %s |\n", r[0], r[1])
	}
	b.WriteString("\n")
}

// latestDeepDive returns the most recent done security-deep-dive scan for
// the repo plus its parsed report JSON (if any).
func latestDeepDive(gdb *gorm.DB, repoID uint) (*db.Scan, map[string]any) {
	var scan db.Scan
	if err := gdb.Where("repository_id = ? AND skill_name = ? AND status = ?",
		repoID, deepDiveSkillName, db.ScanDone).
		Order("id desc").First(&scan).Error; err != nil {
		return nil, nil
	}
	var tm map[string]any
	if scan.Report != "" {
		_ = json.Unmarshal([]byte(scan.Report), &tm)
	}
	return &scan, tm
}

func writeReportThreatModel(b *strings.Builder, scan *db.Scan, tm map[string]any) {
	fmt.Fprintf(b, "## Threat model\n\n")
	if scan == nil {
		fmt.Fprintf(b, "No completed %s scan yet.\n\n", deepDiveSkillName)
		return
	}
	fmt.Fprintf(b, "From scan #%d at commit `%s` (%s).\n\n",
		scan.ID, shortCommit(scan.Commit), formatScanDate(scan))

	if tm == nil {
		fmt.Fprintf(b, "Scan report was not machine-readable.\n\n")
		return
	}

	if boundaries := listSlice(tm, "boundaries"); len(boundaries) > 0 {
		fmt.Fprintf(b, "### Trust boundaries\n\n")
		fmt.Fprintf(b, "| Actor | Trusted | Controls | Source |\n|---|---|---|---|\n")
		for _, x := range boundaries {
			if m, ok := x.(map[string]any); ok {
				fmt.Fprintf(b, "| %s | %s | %s | %s |\n",
					mdCell(m, "actor"), mdCell(m, "trusted"),
					mdCell(m, "controls"), mdCell(m, "source"))
			}
		}
		b.WriteString("\n")
	}

	if narrative, _ := tm["boundaries_narrative"].(string); narrative != "" {
		fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(narrative))
	}

	if inventory := listSlice(tm, "inventory"); len(inventory) > 0 {
		fmt.Fprintf(b, "### Sink inventory\n\n")
		fmt.Fprintf(b, "| # | Class | Primitive | Location | Consumes |\n|---|---|---|---|---|\n")
		for _, x := range inventory {
			if m, ok := x.(map[string]any); ok {
				fmt.Fprintf(b, "| %s | %s | %s | `%s` | %s |\n",
					mdCell(m, "id"), mdCell(m, "class"), mdCell(m, "primitive"),
					mdCell(m, "location"), mdCell(m, "consumes"))
			}
		}
		b.WriteString("\n")
	}

	if ruledOut := listSlice(tm, "ruled_out"); len(ruledOut) > 0 {
		fmt.Fprintf(b, "### Ruled out\n\n")
		for _, x := range ruledOut {
			m, ok := x.(map[string]any)
			if !ok {
				continue
			}
			sinks := strings.Join(stringSlice(m["sinks"]), ", ")
			fmt.Fprintf(b, "**%s** at step %v\n\n", sinks, m["step"])
			if reason, _ := m["reason"].(string); reason != "" {
				fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(reason))
			}
		}
	}

	if prior, _ := tm["prior_art"].(string); prior != "" {
		fmt.Fprintf(b, "### Prior art (report-level)\n\n%s\n\n", strings.TrimSpace(prior))
	}
	if reach, _ := tm["reach"].(string); reach != "" {
		fmt.Fprintf(b, "### Reach (report-level)\n\n%s\n\n", strings.TrimSpace(reach))
	}
}

func writeReportFindings(b *strings.Builder, gdb *gorm.DB, repoID uint, latest *db.Scan) {
	fmt.Fprintf(b, "## Findings\n\n")
	// Mirrors the repo page Findings tab: deep-dive output only. Scanner
	// findings (zizmor, semgrep) belong to the Scanners tab and stay out of
	// the curated report so download recipients don't drown in lint noise.
	var findings []db.Finding
	gdb.Where("repository_id = ?", repoID).
		Where("scan_id IN (?)", deepDiveScanIDs(gdb)).
		Order("severity, id").Find(&findings)
	if len(findings) == 0 {
		fmt.Fprintf(b, "No findings recorded for this repository.\n\n")
		return
	}

	fmt.Fprintf(b, "%d finding(s).\n\n", len(findings))
	fmt.Fprintf(b, "| # | Severity | Status | Title | Location |\n|---|---|---|---|---|\n")
	for _, f := range findings {
		fmt.Fprintf(b, "| %d | %s | %s | %s | `%s` |\n",
			f.ID, f.Severity, f.Status, escapeMD(f.Title), f.Location)
	}
	b.WriteString("\n")

	for _, f := range findings {
		writeReportFinding(b, gdb, f, latest)
	}
}

func writeReportFinding(b *strings.Builder, gdb *gorm.DB, f db.Finding, latest *db.Scan) {
	fmt.Fprintf(b, "### Finding #%d: %s\n\n", f.ID, f.Title)

	rows := [][2]string{
		{"Severity", f.Severity},
		{"Status", string(f.Status)},
		{"CWE", f.CWE},
		{"Location", "`" + f.Location + "`"},
		{"Sinks", f.Sinks},
		{"Affected", f.Affected},
		{"CVE", f.CVEID},
		{"CVSS", f.CVSSVector},
		{"Fix version", f.FixVersion},
		{"Fix commit", f.FixCommit},
		{"Resolution", string(f.Resolution)},
		{"Assignee", f.Assignee},
	}
	if f.CVSSScore > 0 {
		for i := range rows {
			if rows[i][0] == "CVSS" {
				rows[i][1] = fmt.Sprintf("%s (%.1f)", f.CVSSVector, f.CVSSScore)
			}
		}
	}
	fmt.Fprintf(b, "| Field | Value |\n|---|---|\n")
	for _, r := range rows {
		if r[1] == "" {
			continue
		}
		fmt.Fprintf(b, "| %s | %s |\n", r[0], r[1])
	}
	b.WriteString("\n")
	_ = latest // reserved for future use, e.g. linking location to a permalink

	writeProse(b, "#### Trace", f.Trace)
	writeProse(b, "#### Trust boundary", f.Boundary)
	writeProse(b, "#### Validation", f.Validation)
	writeProse(b, "#### Prior art", f.PriorArt)
	writeProse(b, "#### Reach", f.Reach)
	writeProse(b, "#### Rating", f.Rating)

	if f.DisclosureDraft != "" {
		fmt.Fprintf(b, "#### Disclosure draft\n\n%s\n\n", strings.TrimSpace(f.DisclosureDraft))
	}

	writeFindingNotes(b, gdb, f.ID)
	writeFindingCommunications(b, gdb, f.ID)
	writeFindingReferences(b, gdb, f.ID)
	writeFindingLabels(b, gdb, f.ID)
}

func writeProse(b *strings.Builder, heading, body string) {
	if strings.TrimSpace(body) == "" {
		return
	}
	fmt.Fprintf(b, "%s\n\n%s\n\n", heading, strings.TrimSpace(body))
}

func writeFindingNotes(b *strings.Builder, gdb *gorm.DB, findingID uint) {
	var notes []db.FindingNote
	gdb.Where("finding_id = ?", findingID).Order("created_at desc").Find(&notes)
	if len(notes) == 0 {
		return
	}
	fmt.Fprintf(b, "#### Notes\n\n")
	for _, n := range notes {
		who := n.By
		if who == "" {
			who = "analyst"
		}
		fmt.Fprintf(b, "- *%s, %s*:\n\n  %s\n\n",
			who, n.CreatedAt.UTC().Format("2006-01-02 15:04"), indent(strings.TrimSpace(n.Body), "  "))
	}
}

func writeFindingCommunications(b *strings.Builder, gdb *gorm.DB, findingID uint) {
	var comms []db.FindingCommunication
	gdb.Where("finding_id = ?", findingID).Order("at desc").Find(&comms)
	if len(comms) == 0 {
		return
	}
	fmt.Fprintf(b, "#### Communications\n\n")
	for _, c := range comms {
		offer := ""
		if c.OfferedHelp != "" && c.OfferedHelp != "none" {
			offer = " (offered " + c.OfferedHelp + ")"
		}
		fmt.Fprintf(b, "- **%s %s** to/from `%s` on %s%s\n\n  %s\n\n",
			c.Channel, c.Direction, c.Actor, c.At.UTC().Format("2006-01-02"), offer,
			indent(strings.TrimSpace(c.Body), "  "))
	}
}

func writeFindingReferences(b *strings.Builder, gdb *gorm.DB, findingID uint) {
	var refs []db.FindingReference
	gdb.Where("finding_id = ?", findingID).Order("id asc").Find(&refs)
	if len(refs) == 0 {
		return
	}
	fmt.Fprintf(b, "#### References\n\n")
	for _, r := range refs {
		tag := ""
		if r.Tags != "" {
			tag = " — " + r.Tags
		}
		summary := ""
		if r.Summary != "" {
			summary = " (" + r.Summary + ")"
		}
		fmt.Fprintf(b, "- <%s>%s%s\n", r.URL, tag, summary)
	}
	b.WriteString("\n")
}

func writeFindingLabels(b *strings.Builder, gdb *gorm.DB, findingID uint) {
	var f db.Finding
	if err := gdb.Preload("Labels").First(&f, findingID).Error; err != nil || len(f.Labels) == 0 {
		return
	}
	names := make([]string, 0, len(f.Labels))
	for _, l := range f.Labels {
		names = append(names, l.Name)
	}
	fmt.Fprintf(b, "#### Labels\n\n%s\n\n", strings.Join(names, ", "))
}

func writeReportPackages(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var pkgs []db.Package
	gdb.Where("repository_id = ?", repoID).Order("dependent_repos desc, downloads desc").Find(&pkgs)
	if len(pkgs) == 0 {
		return
	}
	fmt.Fprintf(b, "## Packages\n\n| Name | Ecosystem | Latest | Downloads | Dependent repos |\n|---|---|---|---|---|\n")
	for _, p := range pkgs {
		fmt.Fprintf(b, "| %s | %s | %s | %d | %d |\n",
			p.Name, p.Ecosystem, p.LatestVersion, p.Downloads, p.DependentRepos)
	}
	b.WriteString("\n")
}

func writeReportAdvisories(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var rows []db.Advisory
	gdb.Where("repository_id = ?", repoID).Order("cvss_score desc").Find(&rows)
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(b, "## Published advisories\n\n| Severity | CVSS | Title | Packages | URL |\n|---|---|---|---|---|\n")
	for _, a := range rows {
		fmt.Fprintf(b, "| %s | %.1f | %s | %s | %s |\n",
			a.Severity, a.CVSSScore, escapeMD(a.Title), a.Packages, a.URL)
	}
	b.WriteString("\n")
}

func writeReportDependents(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var rows []db.Dependent
	gdb.Where("repository_id = ?", repoID).Order("dependent_repos desc").Limit(reportDependentLimit).Find(&rows)
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(b, "## Top dependents\n\n| Name | Ecosystem | Downloads | Dependent repos |\n|---|---|---|---|\n")
	for _, d := range rows {
		fmt.Fprintf(b, "| %s | %s | %d | %d |\n", d.Name, d.Ecosystem, d.Downloads, d.DependentRepos)
	}
	b.WriteString("\n")
}

func writeReportDependencies(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var rows []db.Dependency
	gdb.Where("repository_id = ?", repoID).Find(&rows)
	if len(rows) == 0 {
		return
	}
	counts := make(map[string]int)
	for _, d := range rows {
		counts[d.Ecosystem]++
	}
	fmt.Fprintf(b, "## Dependencies\n\n%d declared dependencies across %d ecosystem(s):\n\n",
		len(rows), len(counts))
	for eco, n := range counts {
		fmt.Fprintf(b, "- **%s**: %d\n", eco, n)
	}
	b.WriteString("\n")
}

func writeReportMaintainers(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var rows []db.Maintainer
	gdb.Joins("JOIN repository_maintainers rm ON rm.maintainer_id = maintainers.id").
		Where("rm.repository_id = ?", repoID).
		Order("maintainers.login").Find(&rows)
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(b, "## Maintainers\n\n| Name | Login | Email | Status | Notes |\n|---|---|---|---|---|\n")
	for _, m := range rows {
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n",
			m.Name, m.Login, m.Email, m.Status, escapeMD(m.Notes))
	}
	b.WriteString("\n")
}

// reportDependentLimit caps the top-dependents table so a package with
// thousands of dependents doesn't blow out the report length.
const reportDependentLimit = 30

func listSlice(m map[string]any, key string) []any {
	v, ok := m[key].([]any)
	if !ok {
		return nil
	}
	return v
}

func stringSlice(v any) []string {
	s, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(s))
	for _, x := range s {
		if str, ok := x.(string); ok {
			out = append(out, str)
		}
	}
	return out
}

func mdCell(m map[string]any, key string) string {
	v, _ := m[key].(string)
	return escapeMD(v)
}

func escapeMD(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func indent(s, prefix string) string {
	if s == "" {
		return s
	}
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if i == 0 {
			continue
		}
		if line != "" {
			lines[i] = prefix + line
		}
	}
	return strings.Join(lines, "\n")
}

func shortCommit(c string) string {
	const n = 12
	if len(c) > n {
		return c[:n]
	}
	return c
}

func formatScanDate(s *db.Scan) string {
	if s.FinishedAt != nil {
		return s.FinishedAt.UTC().Format("2006-01-02")
	}
	return s.CreatedAt.UTC().Format("2006-01-02")
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if v != "" {
			return v
		}
	}
	return ""
}

func sanitiseFilename(s string) string {
	// Conservative: keep letters, digits, -_. — everything else becomes -.
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9',
			r == '-', r == '_', r == '.':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	out := b.String()
	if out == "" {
		return "repo"
	}
	return out
}
