package web

import (
	"encoding/json"
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"time"

	"gorm.io/gorm"

	"scrutineer/internal/db"
)

// repoReport renders a shareable markdown document covering everything the
// repo page shows: identity, threat model, findings (with six-step prose,
// scoring fields, notes, communications, references), packages, advisories,
// dependents, dependencies, and maintainers. Served as text/markdown with
// a filename hint so clicking the download button saves a file.
func (s *Server) repoReport(w http.ResponseWriter, r *http.Request) {
	repo, ok := loadByID[db.Repository](s, w, r)
	if !ok {
		return
	}

	body := renderRepoReport(s.DB, &repo)

	filename := fmt.Sprintf("scrutineer-%s-%s.md",
		sanitiseFilename(repo.Name),
		time.Now().UTC().Format("20060102"))
	w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
	w.Header().Set("Content-Disposition", `attachment; filename="`+filename+`"`)
	_, _ = w.Write([]byte(body))
}

func renderRepoReport(gdb *gorm.DB, repo *db.Repository) string {
	// Findings and sink dispositions are computed once up front so the
	// summary, threat-model inventory, and findings sections all render
	// from the same data without re-querying.
	latest, threatModel := latestDeepDive(gdb, repo.ID)
	findings := loadReportFindings(gdb, repo.ID)
	disp := buildSinkDispositions(threatModel, latestScanFindings(gdb, latest))

	var b strings.Builder
	writeReportHeader(&b, repo)
	writeReportSummary(&b, latest, findings, disp)
	writeReportMetadata(&b, repo)
	writeReportThreatModel(&b, latest, threatModel, disp)
	writeReportFindings(&b, gdb, findings, latest)
	writeReportPackages(&b, gdb, repo.ID)
	writeReportAdvisories(&b, gdb, repo.ID)
	writeReportDependents(&b, gdb, repo.ID)
	writeReportDependencies(&b, gdb, repo.ID)
	writeReportMaintainers(&b, gdb, repo.ID)

	return b.String()
}

func writeReportHeader(b *strings.Builder, repo *db.Repository) {
	fmt.Fprintf(b, "# %s\n\n", firstNonEmpty(repo.FullName, repo.Name, repo.URL))
	fmt.Fprintf(b, "<%s>\n\n", repo.URL)
	if repo.Description != "" {
		fmt.Fprintf(b, "%s\n\n", repo.Description)
	}
	fmt.Fprintf(b, "Generated by [scrutineer](https://github.com/alpha-omega-security/scrutineer) at %s UTC.\n\n",
		time.Now().UTC().Format("2006-01-02 15:04"))
	fmt.Fprintf(b, "---\n\n")
}

func writeReportMetadata(b *strings.Builder, repo *db.Repository) {
	fmt.Fprintf(b, "## Repository metadata\n\n")
	rows := [][2]string{
		{"URL", repo.URL},
		{"Full name", repo.FullName},
		{"Owner", repo.Owner},
		{"Default branch", repo.DefaultBranch},
		{"Languages", repo.Languages},
		{"License", repo.License},
		{"Stars", fmt.Sprintf("%d", repo.Stars)},
		{"Forks", fmt.Sprintf("%d", repo.Forks)},
		{"Archived", fmt.Sprintf("%t", repo.Archived)},
	}
	if repo.PushedAt != nil {
		rows = append(rows, [2]string{"Last pushed", repo.PushedAt.UTC().Format(time.RFC3339)})
	}
	fmt.Fprintf(b, "| Field | Value |\n|---|---|\n")
	for _, r := range rows {
		if r[1] == "" {
			continue
		}
		fmt.Fprintf(b, "| %s | %s |\n", r[0], r[1])
	}
	b.WriteString("\n")
}

// latestDeepDive returns the most recent done security-deep-dive scan for
// the repo plus its parsed report JSON (if any).
func latestDeepDive(gdb *gorm.DB, repoID uint) (*db.Scan, map[string]any) {
	var scan db.Scan
	if err := gdb.Where("repository_id = ? AND skill_name = ? AND status = ?",
		repoID, deepDiveSkillName, db.ScanDone).
		Order("id desc").First(&scan).Error; err != nil {
		return nil, nil
	}
	var tm map[string]any
	if scan.Report != "" {
		_ = json.Unmarshal([]byte(scan.Report), &tm)
	}
	return &scan, tm
}

// loadReportFindings mirrors the repo page Findings tab: open deep-dive
// findings (closed lifecycles excluded, as the tab does), ordered
// Critical-first then most-recent id, so the summary's top-N and the
// findings section share the same ordering the UI shows.
func loadReportFindings(gdb *gorm.DB, repoID uint) []db.Finding {
	var findings []db.Finding
	gdb.Where("repository_id = ?", repoID).
		Where("status NOT IN ?", db.ClosedFindingLifecycles).
		Where("scan_id IN (?)", deepDiveScanIDs(gdb)).
		Order(severityOrder).Order("id desc").Find(&findings)
	return findings
}

// latestScanFindings loads the findings produced by one scan, for
// resolving sink dispositions. Inventory sink ids (S1, S2, …) are only
// unique within a single deep-dive report, so dispositions must be built
// from the findings of the same scan that produced the inventory; mixing
// in an older scan's findings would let its "S1" claim this scan's
// inventory "S1". All lifecycles are kept on purpose — a sink that became
// a finding is covered even if that finding was later triaged closed.
func latestScanFindings(gdb *gorm.DB, scan *db.Scan) []db.Finding {
	if scan == nil {
		return nil
	}
	var findings []db.Finding
	gdb.Where("scan_id = ?", scan.ID).Find(&findings)
	return findings
}

// sinkDisposition records where one inventory sink id ended up so the
// inventory table can show outcome alongside catalogue and the summary
// can report coverage without the reader cross-referencing the
// inventory and ruled-out sections.
type sinkDisposition struct {
	findingID uint
	ruled     bool
	step      int
	reason    string
}

func (d sinkDisposition) cell() string {
	switch {
	case d.findingID != 0:
		return fmt.Sprintf("→ Finding #%d", d.findingID)
	case d.ruled:
		r := firstClause(d.reason)
		if r == "" {
			return fmt.Sprintf("ruled out, step %d", d.step)
		}
		return fmt.Sprintf("ruled out, step %d — %s", d.step, r)
	default:
		return "unresolved"
	}
}

// buildSinkDispositions maps each inventory sink id to its outcome. The
// deep-dive skill guarantees every inventory entry lands in either a
// finding's Sinks or a ruled_out entry, so anything left over is a
// coverage gap worth surfacing as "unresolved". A sink claimed by both
// keeps the finding outcome since that is the actionable one.
func buildSinkDispositions(tm map[string]any, findings []db.Finding) map[string]sinkDisposition {
	inv := listSlice(tm, "inventory")
	if len(inv) == 0 {
		return nil
	}
	disp := make(map[string]sinkDisposition, len(inv))
	for _, x := range inv {
		if m, ok := x.(map[string]any); ok {
			if id, _ := m["id"].(string); id != "" {
				disp[id] = sinkDisposition{}
			}
		}
	}
	for _, x := range listSlice(tm, "ruled_out") {
		m, ok := x.(map[string]any)
		if !ok {
			continue
		}
		step := intVal(m["step"])
		reason, _ := m["reason"].(string)
		for _, id := range stringSlice(m["sinks"]) {
			if _, ok := disp[id]; ok {
				disp[id] = sinkDisposition{ruled: true, step: step, reason: reason}
			}
		}
	}
	for _, f := range findings {
		for _, id := range splitSinks(f.Sinks) {
			if _, ok := disp[id]; ok {
				disp[id] = sinkDisposition{findingID: f.ID}
			}
		}
	}
	return disp
}

// dispositionCounts returns (ruled out, became findings, unresolved). The
// catalogued count is len(disp).
func dispositionCounts(disp map[string]sinkDisposition) (ruled, found, unresolved int) {
	for _, d := range disp {
		switch {
		case d.findingID != 0:
			found++
		case d.ruled:
			ruled++
		default:
			unresolved++
		}
	}
	return ruled, found, unresolved
}

const summaryTopN = 3

// writeReportSummary emits a five-line block a maintainer can read in
// thirty seconds: severity counts, top findings, sink coverage, where
// to start, and which tree it applies to. Upstream feedback was that
// the full report takes hours to digest before it is actionable; this
// gives them the headline first.
func writeReportSummary(b *strings.Builder, scan *db.Scan, findings []db.Finding, disp map[string]sinkDisposition) {
	if scan == nil && len(findings) == 0 {
		return
	}
	fmt.Fprintf(b, "## Summary\n\n")

	by := severityCounts(findings)
	fmt.Fprintf(b, "- %d findings: %d critical, %d high, %d medium, %d low\n",
		len(findings), by["Critical"], by["High"], by["Medium"], by["Low"])

	for i, f := range findings {
		if i >= summaryTopN {
			break
		}
		fmt.Fprintf(b, "- **%s** — Finding #%d, %s\n", escapeMD(f.Title), f.ID, f.Severity)
	}

	if len(disp) > 0 {
		ruled, found, unresolved := dispositionCounts(disp)
		fmt.Fprintf(b, "- Sink coverage: %d catalogued, %d ruled out, %d became findings, %d unresolved\n",
			len(disp), ruled, found, unresolved)
	}

	if len(findings) > 0 {
		fmt.Fprintf(b, "- Start with Finding #%d\n", findings[0].ID)
	}

	if scan != nil {
		fmt.Fprintf(b, "- Scan at commit `%s` (%s)\n", shortCommit(scan.Commit), formatScanDate(scan))
	}
	b.WriteString("\n")
}

func severityCounts(findings []db.Finding) map[string]int {
	by := make(map[string]int, len(db.SeverityLevels))
	for _, f := range findings {
		by[f.Severity]++
	}
	return by
}

func writeReportThreatModel(b *strings.Builder, scan *db.Scan, tm map[string]any, disp map[string]sinkDisposition) {
	fmt.Fprintf(b, "## Threat model\n\n")
	if scan == nil {
		fmt.Fprintf(b, "No completed %s scan yet.\n\n", deepDiveSkillName)
		return
	}
	if scan.SkillsRepoSHA != "" {
		fmt.Fprintf(b, "From scan #%d at commit `%s` (%s) — skills repo `%s`.\n\n",
			scan.ID, shortCommit(scan.Commit), formatScanDate(scan), shortCommit(scan.SkillsRepoSHA))
	} else {
		fmt.Fprintf(b, "From scan #%d at commit `%s` (%s).\n\n",
			scan.ID, shortCommit(scan.Commit), formatScanDate(scan))
	}

	if tm == nil {
		fmt.Fprintf(b, "Scan report was not machine-readable.\n\n")
		return
	}

	if boundaries := listSlice(tm, "boundaries"); len(boundaries) > 0 {
		fmt.Fprintf(b, "### Trust boundaries\n\n")
		fmt.Fprintf(b, "| Actor | Trusted | Controls | Source |\n|---|---|---|---|\n")
		for _, x := range boundaries {
			if m, ok := x.(map[string]any); ok {
				fmt.Fprintf(b, "| %s | %s | %s | %s |\n",
					mdCell(m, "actor"), mdCell(m, "trusted"),
					mdCell(m, "controls"), mdCell(m, "source"))
			}
		}
		b.WriteString("\n")
	}

	if narrative, _ := tm["boundaries_narrative"].(string); narrative != "" {
		fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(narrative))
	}

	if inventory := listSlice(tm, "inventory"); len(inventory) > 0 {
		fmt.Fprintf(b, "### Sink inventory\n\n")
		fmt.Fprintf(b, "| # | Class | Primitive | Location | Consumes | Disposition |\n|---|---|---|---|---|---|\n")
		for _, x := range inventory {
			if m, ok := x.(map[string]any); ok {
				id, _ := m["id"].(string)
				fmt.Fprintf(b, "| %s | %s | %s | `%s` | %s | %s |\n",
					escapeMD(id), mdCell(m, "class"), mdCell(m, "primitive"),
					mdCell(m, "location"), mdCell(m, "consumes"),
					escapeMD(disp[id].cell()))
			}
		}
		b.WriteString("\n")
	}

	if ruledOut := listSlice(tm, "ruled_out"); len(ruledOut) > 0 {
		fmt.Fprintf(b, "### Ruled out\n\n")
		for _, x := range ruledOut {
			m, ok := x.(map[string]any)
			if !ok {
				continue
			}
			sinks := strings.Join(stringSlice(m["sinks"]), ", ")
			fmt.Fprintf(b, "**%s** at step %v\n\n", sinks, m["step"])
			if reason, _ := m["reason"].(string); reason != "" {
				fmt.Fprintf(b, "%s\n\n", strings.TrimSpace(reason))
			}
		}
	}

	if prior, _ := tm["prior_art"].(string); prior != "" {
		fmt.Fprintf(b, "### Prior art (report-level)\n\n%s\n\n", strings.TrimSpace(prior))
	}
	if reach, _ := tm["reach"].(string); reach != "" {
		fmt.Fprintf(b, "### Reach (report-level)\n\n%s\n\n", strings.TrimSpace(reach))
	}
}

func writeReportFindings(b *strings.Builder, gdb *gorm.DB, findings []db.Finding, latest *db.Scan) {
	fmt.Fprintf(b, "## Findings\n\n")
	if len(findings) == 0 {
		fmt.Fprintf(b, "No findings recorded for this repository.\n\n")
		return
	}

	fmt.Fprintf(b, "%d finding(s).\n\n", len(findings))
	fmt.Fprintf(b, "| # | Severity | Status | Title | Location |\n|---|---|---|---|---|\n")
	for _, f := range findings {
		fmt.Fprintf(b, "| %d | %s | %s | %s | `%s` |\n",
			f.ID, f.Severity, f.Status, escapeMD(f.Title), f.Location)
	}
	b.WriteString("\n")

	for _, f := range findings {
		writeReportFinding(b, gdb, f, latest)
	}
}

func writeReportFinding(b *strings.Builder, gdb *gorm.DB, f db.Finding, latest *db.Scan) {
	fmt.Fprintf(b, "### Finding #%d: %s\n\n", f.ID, f.Title)

	rows := [][2]string{
		{"Severity", f.Severity},
		{"Status", string(f.Status)},
		{"CWE", f.CWE},
		{"Location", "`" + f.Location + "`"},
		{"Sinks", f.Sinks},
		{"Affected", f.Affected},
		{"Exploited in wild", f.ExploitedInWild},
		{"CVE", f.CVEID},
		{"GHSA", f.GHSAID},
		{"CVSS", f.CVSSVector},
		{"Fix version", f.FixVersion},
		{"Fix commit", f.FixCommit},
		{"Resolution", string(f.Resolution)},
		{"Assignee", f.Assignee},
	}
	if f.CVSSScore > 0 {
		for i := range rows {
			if rows[i][0] == "CVSS" {
				rows[i][1] = fmt.Sprintf("%s (%.1f)", f.CVSSVector, f.CVSSScore)
			}
		}
	}
	fmt.Fprintf(b, "| Field | Value |\n|---|---|\n")
	for _, r := range rows {
		if r[1] == "" {
			continue
		}
		fmt.Fprintf(b, "| %s | %s |\n", r[0], r[1])
	}
	b.WriteString("\n")
	_ = latest // reserved for future use, e.g. linking location to a permalink

	// For findings the worker grouped across multiple match positions
	// (#193 — same rule firing in many file:lines collapsed into one
	// row whose Locations column carries the full set), list the
	// additional positions so the markdown export shows the same scope
	// the finding_show.html "N more locations" details block does.
	// Sorted by (path, line-as-int) so within a single file lines
	// appear in ascending numeric order rather than lexicographic
	// (which puts :110 before :56).
	if f.ExtraLocationCount() > 0 {
		locs := f.LocationList()[1:]
		sort.Slice(locs, func(i, j int) bool {
			return locationLess(locs[i], locs[j])
		})
		fmt.Fprintf(b, "#### Additional locations\n\n")
		for _, loc := range locs {
			fmt.Fprintf(b, "- `%s`\n", loc)
		}
		b.WriteString("\n")
	}

	writeProse(b, "#### Trace", f.Trace)
	writeProse(b, "#### Trust boundary", f.Boundary)
	writeProse(b, "#### Validation", f.Validation)
	writeProse(b, "#### Prior art", f.PriorArt)
	writeProse(b, "#### Reach", f.Reach)
	writeProse(b, "#### Rating", f.Rating)

	if f.ExploitedInWild != "" && f.ExploitedInWildEvidence != "" {
		fmt.Fprintf(b, "#### Exploitation status\n\nExploited in wild: **%s**.\n\n%s\n\n",
			f.ExploitedInWild, strings.TrimSpace(f.ExploitedInWildEvidence))
	}

	if f.DisclosureDraft != "" {
		fmt.Fprintf(b, "#### Disclosure draft\n\n%s\n\n", strings.TrimSpace(f.DisclosureDraft))
	}

	if f.Mitigation != "" {
		fmt.Fprintf(b, "#### Mitigation\n\n%s\n\n", strings.TrimSpace(f.Mitigation))
		if f.MitigationSemgrep != "" {
			fmt.Fprintf(b, "##### Semgrep rule\n\n```yaml\n%s\n```\n\n", strings.TrimSpace(f.MitigationSemgrep))
		}
	}

	if f.SuggestedFix != "" {
		fmt.Fprintf(b, "#### Suggested fix\n\n")
		if f.SuggestedFixCommit != "" {
			fmt.Fprintf(b, "Applies to commit `%s`.\n\n", f.SuggestedFixCommit)
		}
		fmt.Fprintf(b, "```diff\n%s\n```\n\n", strings.TrimSpace(f.SuggestedFix))
	}

	writeFindingNotes(b, gdb, f.ID)
	writeFindingCommunications(b, gdb, f.ID)
	writeFindingReferences(b, gdb, f.ID)
	writeFindingLabels(b, gdb, f.ID)
}

func writeProse(b *strings.Builder, heading, body string) {
	if strings.TrimSpace(body) == "" {
		return
	}
	fmt.Fprintf(b, "%s\n\n%s\n\n", heading, strings.TrimSpace(body))
}

func writeFindingNotes(b *strings.Builder, gdb *gorm.DB, findingID uint) {
	var notes []db.FindingNote
	gdb.Where("finding_id = ?", findingID).Order("created_at desc").Find(&notes)
	if len(notes) == 0 {
		return
	}
	fmt.Fprintf(b, "#### Notes\n\n")
	for _, n := range notes {
		who := n.By
		if who == "" {
			who = "analyst"
		}
		fmt.Fprintf(b, "- *%s, %s*:\n\n  %s\n\n",
			who, n.CreatedAt.UTC().Format("2006-01-02 15:04"), indent(strings.TrimSpace(n.Body), "  "))
	}
}

func writeFindingCommunications(b *strings.Builder, gdb *gorm.DB, findingID uint) {
	var comms []db.FindingCommunication
	gdb.Where("finding_id = ?", findingID).Order("at desc").Find(&comms)
	if len(comms) == 0 {
		return
	}
	fmt.Fprintf(b, "#### Communications\n\n")
	for _, c := range comms {
		offer := ""
		if c.OfferedHelp != "" && c.OfferedHelp != "none" {
			offer = " (offered " + c.OfferedHelp + ")"
		}
		fmt.Fprintf(b, "- **%s %s** to/from `%s` on %s%s\n\n  %s\n\n",
			c.Channel, c.Direction, c.Actor, c.At.UTC().Format("2006-01-02"), offer,
			indent(strings.TrimSpace(c.Body), "  "))
	}
}

func writeFindingReferences(b *strings.Builder, gdb *gorm.DB, findingID uint) {
	var refs []db.FindingReference
	gdb.Where("finding_id = ?", findingID).Order("id asc").Find(&refs)
	if len(refs) == 0 {
		return
	}
	fmt.Fprintf(b, "#### References\n\n")
	for _, r := range refs {
		tag := ""
		if r.Tags != "" {
			tag = " — " + r.Tags
		}
		summary := ""
		if r.Summary != "" {
			summary = " (" + r.Summary + ")"
		}
		fmt.Fprintf(b, "- <%s>%s%s\n", r.URL, tag, summary)
	}
	b.WriteString("\n")
}

func writeFindingLabels(b *strings.Builder, gdb *gorm.DB, findingID uint) {
	var f db.Finding
	if err := gdb.Preload("Labels").First(&f, findingID).Error; err != nil || len(f.Labels) == 0 {
		return
	}
	names := make([]string, 0, len(f.Labels))
	for _, l := range f.Labels {
		names = append(names, l.Name)
	}
	fmt.Fprintf(b, "#### Labels\n\n%s\n\n", strings.Join(names, ", "))
}

func writeReportPackages(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var pkgs []db.Package
	gdb.Where("repository_id = ?", repoID).Order("dependent_repos desc, downloads desc").Find(&pkgs)
	if len(pkgs) == 0 {
		return
	}
	fmt.Fprintf(b, "## Packages\n\n| Name | Ecosystem | Latest | Downloads | Dependent repos |\n|---|---|---|---|---|\n")
	for _, p := range pkgs {
		fmt.Fprintf(b, "| %s | %s | %s | %d | %d |\n",
			p.Name, p.Ecosystem, p.LatestVersion, p.Downloads, p.DependentRepos)
	}
	b.WriteString("\n")
}

func writeReportAdvisories(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var rows []db.Advisory
	gdb.Where("repository_id = ?", repoID).Order("cvss_score desc").Find(&rows)
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(b, "## Published advisories\n\n| Severity | CVSS | Title | Packages | URL |\n|---|---|---|---|---|\n")
	for _, a := range rows {
		fmt.Fprintf(b, "| %s | %.1f | %s | %s | %s |\n",
			a.Severity, a.CVSSScore, escapeMD(a.Title), a.Packages, a.URL)
	}
	b.WriteString("\n")
}

func writeReportDependents(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var rows []db.Dependent
	gdb.Where("repository_id = ?", repoID).Order("dependent_repos desc").Limit(reportDependentLimit).Find(&rows)
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(b, "## Top dependents\n\n| Name | Ecosystem | Downloads | Dependent repos |\n|---|---|---|---|\n")
	for _, d := range rows {
		fmt.Fprintf(b, "| %s | %s | %d | %d |\n", d.Name, d.Ecosystem, d.Downloads, d.DependentRepos)
	}
	b.WriteString("\n")
}

func writeReportDependencies(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var rows []db.Dependency
	gdb.Where("repository_id = ?", repoID).Find(&rows)
	if len(rows) == 0 {
		return
	}
	counts := make(map[string]int)
	for _, d := range rows {
		counts[d.Ecosystem]++
	}
	fmt.Fprintf(b, "## Dependencies\n\n%d declared dependencies across %d ecosystem(s):\n\n",
		len(rows), len(counts))
	for eco, n := range counts {
		fmt.Fprintf(b, "- **%s**: %d\n", eco, n)
	}
	b.WriteString("\n")
}

func writeReportMaintainers(b *strings.Builder, gdb *gorm.DB, repoID uint) {
	var rows []db.Maintainer
	gdb.Joins("JOIN repository_maintainers rm ON rm.maintainer_id = maintainers.id").
		Where("rm.repository_id = ?", repoID).
		Order("maintainers.login").Find(&rows)
	if len(rows) == 0 {
		return
	}
	fmt.Fprintf(b, "## Maintainers\n\n| Name | Login | Email | Status | Notes |\n|---|---|---|---|---|\n")
	for _, m := range rows {
		fmt.Fprintf(b, "| %s | %s | %s | %s | %s |\n",
			m.Name, m.Login, m.Email, m.Status, escapeMD(m.Notes))
	}
	b.WriteString("\n")
}

// reportDependentLimit caps the top-dependents table so a package with
// thousands of dependents doesn't blow out the report length.
const reportDependentLimit = 30

func listSlice(m map[string]any, key string) []any {
	v, ok := m[key].([]any)
	if !ok {
		return nil
	}
	return v
}

func stringSlice(v any) []string {
	s, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(s))
	for _, x := range s {
		if str, ok := x.(string); ok {
			out = append(out, str)
		}
	}
	return out
}

func mdCell(m map[string]any, key string) string {
	v, _ := m[key].(string)
	return escapeMD(v)
}

// intVal extracts an int from an untyped JSON value. encoding/json
// decodes numbers as float64 by default; ruled_out.step is documented
// as an integer so the truncation is exact in practice.
func intVal(v any) int {
	switch n := v.(type) {
	case float64:
		return int(n)
	case int:
		return n
	}
	return 0
}

// splitSinks tokenises a Finding.Sinks column ("S1, S2") into ids.
// findings.go writes them comma-joined with a trailing space; older
// rows might lack the space, so trim each token.
func splitSinks(s string) []string {
	if s == "" {
		return nil
	}
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}

// firstClause returns the text up to the first sentence or clause
// terminator, trimmed. Used to fit a ruled-out reason into one
// inventory-table cell while the full prose stays in the Ruled out
// section below.
func firstClause(s string) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexAny(s, ".;\n"); i >= 0 {
		s = s[:i]
	}
	return strings.TrimSpace(s)
}

func escapeMD(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

func indent(s, prefix string) string {
	if s == "" {
		return s
	}
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		if i == 0 {
			continue
		}
		if line != "" {
			lines[i] = prefix + line
		}
	}
	return strings.Join(lines, "\n")
}

func shortCommit(c string) string {
	const n = 12
	if len(c) > n {
		return c[:n]
	}
	return c
}

func formatScanDate(s *db.Scan) string {
	if s.FinishedAt != nil {
		return s.FinishedAt.UTC().Format("2006-01-02")
	}
	return s.CreatedAt.UTC().Format("2006-01-02")
}

func sanitiseFilename(s string) string {
	// Conservative: keep letters, digits, -_. — everything else becomes -.
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9',
			r == '-', r == '_', r == '.':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	out := b.String()
	if out == "" {
		return "repo"
	}
	return out
}

// locationLess sorts file:line strings naturally: by file path first,
// then by line number as an integer. Without this, "x.html:110" sorts
// before "x.html:56" because '1' < '5' lexicographically, which surprises
// a reader scanning a multi-line list.
func locationLess(a, b string) bool {
	ap, al := splitFileLine(a)
	bp, bl := splitFileLine(b)
	if ap != bp {
		return ap < bp
	}
	return al < bl
}

// splitFileLine splits a "path:line" location string. LastIndex handles
// Windows-style paths that contain colons; an unparseable line number
// degrades to 0 so the location still sorts (by path) instead of panicking.
func splitFileLine(s string) (path string, line int) {
	i := strings.LastIndex(s, ":")
	if i < 0 {
		return s, 0
	}
	n, err := strconv.Atoi(s[i+1:])
	if err != nil {
		return s, 0
	}
	return s[:i], n
}
