version: "2"

linters:
  enable:
    - gocritic
    - gocognit
    - gocyclo
    - maintidx
    - dupl
    - mnd
    - unparam
    - ireturn
    - goconst
    - errcheck
  settings:
    goconst:
      min-occurrences: 10
      ignore-tests: true

formatters:
  enable:
    - gofmt
